version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress-data:/var/www
      - openssl-data:/var/ssl
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
      - openssl
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www
    networks:
      - inception
    env_file:
      - .env_db
      - .env_wp
    depends_on:
      - mariadb
      - redis
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env_db
    restart: on-failure
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    volumes:
      - openssl-data:/var/ssl
    networks:
      - inception
    depends_on:
      - openssl
    restart: on-failure
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    volumes:
      - adminer-data:/var/www
      - openssl-data:/var/ssl
    ports:
      - 8080:8080
    networks:
      - inception
    depends_on:
      - mariadb
      - openssl
    restart: on-failure
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    volumes:
      - wordpress-data:/var/wordpress
      - openssl-data:/var/ssl
    ports:
      - 21:21
      - 21000-21100:21000-21100
    networks:
      - inception
    depends_on:
      - wordpress
      - openssl
    env_file:
      - .env_ftp
    restart: on-failure
  openssl:
    container_name: openssl
    build: ./requirements/bonus/openssl
    volumes:
      - openssl-data:/var/ssl
    networks:
      - inception
    env_file:
      - .env_cert
    restart: on-failure

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      device: /home/luca/data/wordpress
      type: none
      o: bind
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      device: /home/luca/data/mariadb
      type: none
      o: bind
  adminer-data:
    name: adminer-data
    driver: local
    driver_opts:
      device: /home/luca/data/adminer
      type: none
      o: bind
  openssl-data:
    name: openssl-data
    driver: local
    driver_opts:
      device: /home/luca/data/openssl
      type: none
      o: bind

networks:
  inception:
    driver: bridge
