version: '3.8'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    volumes:
      - openssl-data:/var/ssl
      - wordpress-data:/var/www
    ports:
      - 443:443
    networks:
      - inception
    env_file:
      - .env_cert
    depends_on:
      - wordpress
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-data:/var/www
    networks:
      - inception
    env_file:
      - .env_db
      - .env_wp
    depends_on:
      - mariadb
      - redis
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env_db
    restart: on-failure
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis
    volumes:
      - openssl-data:/var/ssl
    networks:
      - inception
    restart: on-failure
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer
    volumes:
      - adminer-data:/var/www
      - openssl-data:/var/ssl
    ports:
      - 3000:3000
    networks:
      - inception
    depends_on:
      - mariadb
      - nginx
    restart: on-failure
  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    image: vsftpd
    volumes:
      - wordpress-data:/var/wordpress
      - openssl-data:/var/ssl
    ports:
      - 21:21
      - 21000-21100:21000-21100
    networks:
      - inception
    depends_on:
      - wordpress
      - nginx
    env_file:
      - .env_ftp
    restart: on-failure
  static:
    container_name: static
    build: ./requirements/bonus/static
    image: static
    volumes:
      - static-data:/var/www
    ports:
      - 4242:4242
    networks:
      - inception
    restart: on-failure
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - inception

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      device: /home/lray/data/wordpress
      type: none
      o: bind
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      device: /home/lray/data/mariadb
      type: none
      o: bind
  adminer-data:
    name: adminer-data
    driver: local
    driver_opts:
      device: /home/lray/data/adminer
      type: none
      o: bind
  openssl-data:
    name: openssl-data
    driver: local
    driver_opts:
      device: /home/lray/data/openssl
      type: none
      o: bind
  static-data:
    name: static-data
    driver: local
    driver_opts:
      device: /home/lray/data/static
      type: none
      o: bind

networks:
  inception:
    driver: bridge
